# Generated by Django 4.0.1 on 2022-01-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_label_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
