# Generated by Django 4.0.1 on 2022-01-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
