# Generated by Django 4.0.1 on 2022-01-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
