# Generated by Django 4.0.1 on 2022-01-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='dis_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
