# Generated by Django 4.0.1 on 2022-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_orderitem_isorderd_orderitem_qty_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
