# Generated by Django 4.0.1 on 2022-01-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0014_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Item',
            new_name='items',
        ),
    ]
