# Generated by Django 4.0.1 on 2022-01-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0016_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcard',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecommerce.billingaddress'),
        ),
    ]
