# Generated by Django 4.0.1 on 2022-01-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0019_payment_shopingcard_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ammount',
            new_name='amount',
        ),
    ]
